steps:
  - id: SA Key Automation ForgedFiber37
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: bash
    args:
      - -c
      - |
        set -e

        if [[ -z "${_SA_EMAIL}" ]]; then
          echo "ERROR: _SA_EMAIL substitution is mandatory."
          echo "Please provide a Service Account email while running the trigger."
          exit 1
        fi

        #apt-get update
        apt-get install -y jq
        jq --version

        chmod +x scripts/rotate-sa-key.sh

        echo "Service Account: ${_SA_EMAIL}"

        ./scripts/rotate-sa-key.sh "${_SA_EMAIL}"

substitutions:
  _SA_EMAIL: ""

options:
  logging: CLOUD_LOGGING_ONLY
