steps:
  - name: SA Key Automation ForgedFiber37
    entrypoint: bash
    args:
      - -c
      - |
        apt-get update
        apt-get install -y jq

        chmod +x rotate-if-needed.sh

        echo "SA Email: ${_SA_EMAIL}"

        ./rotate-if-needed.sh "${_SA_EMAIL}"

substitutions:
  _SA_EMAIL: ""

options:
  logging: CLOUD_LOGGING_ONLY
