steps:
  - id: SA Key Automation ForgedFiber37
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: bash
    args:
      - -c
      - |
        set -e

        export DEBIAN_FRONTEND=noninteractive

        if [[ -z "${_SA_EMAIL}" ]]; then
          echo "ERROR: _SA_EMAIL substitution is mandatory."
          exit 1
        fi

        apt-get update
        apt-get install -y jq

        chmod +x scripts/rotate-sa-key.sh

        echo "Service Account : ${_SA_EMAIL}"
        echo "Delete Keys     : ${_DELETE_EXPIRED_KEYS}"
        echo "Key ID          : ${_KEY_ID}"

        ./scripts/rotate-sa-key.sh \
          "${_SA_EMAIL}" \
          "${_DELETE_EXPIRED_KEYS}" \
          "${_KEY_ID}"

substitutions:
  _SA_EMAIL: ""
  _DELETE_EXPIRED_KEYS: "false"
  _KEY_ID: ""

options:
  logging: CLOUD_LOGGING_ONLY
